spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://turntable.proxy.rlwy.net:26364/tstDb
    username: root
    password: CHsXFfTMimNsRbOAVnSSJcqdNBgrMyTV
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true

openapi:
  service:
    api-docs: api service
    server: http://localhost:8080
    title: API Service demo
    version: 1.0
jwt:
  secretKey: dev

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
